export const INTEGRATION_BASE_PATH = '/api/v6/integration';

export const INTEGRATION_OPERATIONS = [
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}`, auth: 'public', description: 'Integration API manifest and authentication guidance.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/operations`, auth: 'public', description: 'List all integration-facing operations exposed by the facade.' },
  { method: 'POST', path: `${INTEGRATION_BASE_PATH}/code/run`, auth: 'bearer | x-api-key', description: 'Run the orchestration pipeline headlessly. Postman-friendly; socketId is optional.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/code/jobs/{jobId}`, auth: 'bearer | x-api-key', description: 'Fetch queued orchestration job status.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/vfs/pending`, auth: 'bearer | x-api-key', description: 'List staged files pending review for the scoped user.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/vfs/stats`, auth: 'bearer | x-api-key', description: 'Return VFS staging statistics for the scoped user.' },
  { method: 'POST', path: `${INTEGRATION_BASE_PATH}/vfs/commit`, auth: 'bearer | x-api-key', description: 'Approve or reject a staged file and optionally commit it to disk.' },
  { method: 'POST', path: `${INTEGRATION_BASE_PATH}/repos/link`, auth: 'bearer | x-api-key', description: 'Attach a repository URL to the scoped integration user.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/repos`, auth: 'bearer | x-api-key', description: 'List linked repositories for the scoped user.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/mcp/tools`, auth: 'bearer | x-api-key', description: 'List discovered MCP tools available to the backend.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/mcp/servers`, auth: 'bearer | x-api-key', description: 'List registered MCP servers.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/mcp/diagnostics`, auth: 'bearer | x-api-key', description: 'Return MCP diagnostics for the current backend instance.' },
  { method: 'POST', path: `${INTEGRATION_BASE_PATH}/mcp/call`, auth: 'bearer | x-api-key', description: 'Invoke an MCP tool by toolId with arguments.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/runtime/diagnostics`, auth: 'bearer | x-api-key', description: 'Return model-runtime diagnostics.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/runtime/experts`, auth: 'bearer | x-api-key', description: 'Return expert-routing diagnostics.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/runtime/skills`, auth: 'bearer | x-api-key', description: 'Return the active skill graph.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/runtime/brand`, auth: 'public', description: 'Return public product and brand metadata.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/audit-logs`, auth: 'bearer | x-api-key', description: 'List audit logs for the scoped user.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/chat/sessions`, auth: 'bearer | x-api-key', description: 'List chat sessions for the scoped user.' },
  { method: 'POST', path: `${INTEGRATION_BASE_PATH}/chat/sessions`, auth: 'bearer | x-api-key', description: 'Create a chat session for the scoped user.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/chat/sessions/{id}/messages`, auth: 'bearer | x-api-key', description: 'List chat messages for a session.' },
  { method: 'POST', path: `${INTEGRATION_BASE_PATH}/chat/sessions/{id}/messages`, auth: 'bearer | x-api-key', description: 'Append a message to a chat session.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/preferences`, auth: 'bearer | x-api-key', description: 'Read user preferences.' },
  { method: 'POST', path: `${INTEGRATION_BASE_PATH}/preferences`, auth: 'bearer | x-api-key', description: 'Upsert a preference document.' },
  { method: 'POST', path: `${INTEGRATION_BASE_PATH}/preferences/bulk`, auth: 'bearer | x-api-key', description: 'Bulk-update user preferences.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/runs/{runId}`, auth: 'bearer | x-api-key', description: 'Read an orchestration run record.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/runs/{runId}/events`, auth: 'bearer | x-api-key', description: 'Read orchestration run events.' },
  { method: 'GET', path: `${INTEGRATION_BASE_PATH}/runs/{runId}/artifacts`, auth: 'bearer | x-api-key', description: 'Read orchestration run artifacts.' },
  { method: 'POST', path: `${INTEGRATION_BASE_PATH}/approvals/grants`, auth: 'bearer | x-api-key', description: 'Create an approval grant for a pending tool action.' },
];
